### ISSUE TITLE
Write project in TypeScript

### ISSUE THREAD

**Issue by Shinigami92** [rashfael/vue-eslint-parser-template-tokenizer-pug#1]
I would love to write this tokenizer directly in TypeScript.
I could help with that if you need help.
Then I can use it later in my plugin directly without the need of writing manual types or something like that and experience native TS support

**Comment by rashfael** [comment]
This package is not statically imported anywhere, so there are no types to expose really (it's dymically imported directly by vue-eslint-parser). I personally prefer plain javascript and would like to keep this project as plain js for the time being, at least until it's stable.
